name: Build with dotnet publish on Windows and Linux
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  dotnet-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Specify the operating systems
    runs-on: ${{ matrix.os }} # Runs the job on the OS specified in the matrix
  
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0 # Replace with the version of .NET you need

      # Publish the application
      - name: Publish the application
        working-directory: src
        run: dotnet publish -o publish-output # Output files to "publish-output" directory

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: published-app-${{ matrix.os }} # Name of the artifact, differentiating by OS
          path: src/publish-output # Path where the application was published

  create-release:
    needs: dotnet-publish # Runs after the dotnet-publish job
    runs-on: ubuntu-latest # Can run this on any OS since it's uploading artifacts
    
    steps:

      # Download artifacts from the dotnet-publish job for all OSes
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app-ubuntu-latest
          path: ubuntu-artifacts
        
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app-windows-latest
          path: windows-artifacts

      # Create a GitHub release (using the Ubuntu and Windows artifacts)
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            This release contains the build artifacts for the following operating systems:
            - Ubuntu
            - Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Ubuntu artifact to the release
      - name: Upload Ubuntu artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ubuntu-artifacts
          asset_name: published-app-ubuntu-latest.zip
          asset_content_type: application/zip

      # Upload Windows artifact to the release
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: windows-artifacts
          asset_name: published-app-windows-latest.zip
          asset_content_type: application/zip